### ISSUE TITLE
How to run WooCommerce core tests?

### ISSUE THREAD

**Issue by BrianHenryIE** [woocommerce/woocommerce-e2e-boilerplate#11]
I'm trying, without luck, to run the tests in `node_modules/@woocommerce/e2e-core-tests/specs` directory. i.e. I want to confirm my plugin is not breaking anything in core. I have what should be a failing test – a plugin where I was hooking too early and could no longer change product images ([a related issue](https://wordpress.org/support/topic/amzon-pay-pluggin-conflict/)).

I've toyed around with the Jest config, in particular removing the default exclusion on `node_modules` (`NODE_MODULES_REGEXP`) and adding the path to the core tests:

```
const jestConfig = useE2EJestConfig( {
	roots: [ path.resolve( __dirname, '../specs' ), path.resolve( __dirname, '../../../node_modules/@woocommerce/e2e-core-tests/specs' ) ],
	testMatch: [ '**/*.(test|spec).js', '*.(test|spec).js', 'index.js'],
	testPathIgnorePatterns: []
} );
```

but I still get `No tests found`:

```
npm  run test:e2e node_modules/@woocommerce/e2e-core-tests/specs
```
```
> bh-wc-set-gateway-by-url@1.0.6 test:e2e /Users/brianhenry/Sites/bh-wc-set-gateway-by-url
> npx wc-e2e test:e2e "node_modules/@woocommerce/e2e-core-tests/specs"

Testing URL: http://localhost:8084

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
No files found in /Users/brianhenry/Sites/bh-wc-set-gateway-by-url/node_modules/@woocommerce/e2e-environment.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern: node_modules/@woocommerce/e2e-core-tests/specs - 0 matches
Jest exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bh-wc-set-gateway-by-url@1.0.6 test:e2e: `npx wc-e2e test:e2e "node_modules/@woocommerce/e2e-core-tests/specs"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bh-wc-set-gateway-by-url@1.0.6 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/brianhenry/.npm/_logs/2021-07-09T17_10_51_761Z-debug.log
```

In the future, I hope all plugins on the WooCommerce store will be obliged to publish their tests so we can run them with our own plugins active.

**Comment by rrennick** [comment]
> but I still get No tests found:

@BrianHenryIE All the tests are wrapped in functions. To use the tests you need to create a local test spec and use the test function:

```
const { runActivationTest } = require( '@woocommerce/e2e-core-tests' );

runActivationTest();
```

Thanks for calling this out. I'll leave this open for adding some instructions.

**Comment by BrianHenryIE** [comment]
Thanks for the instruction. That one example does pass but when I try to run them all they generally fail.

_Without_ my plugin being active

```
const { runShopperTests } = require( '@woocommerce/e2e-core-tests' );

runShopperTests();
```

results in 35 failed, 2 skipped, 21 passed, with various `No node found for selector`, `TimeoutError: Element ... not found`, `TypeError: Cannot read property 'click' of undefined`.

I notice the e2e-core-tests package is a few months old, so possibly they are passing tests for the WooCommerce version that was current when the package was released.

I checked out the tests as they stood when the current version of WooCommerce (5.6.0) was released but just got another error (`Configuration property "products.variable.attributes" is not defined`).

As I was troubleshooting, I noticed another folder of tests in the WooCommerce repo at [tests/e2e/specs](https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/specs), in addition to those at [tests/e2e/core-tests/specs](https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e/core-tests/specs). Ideally, I'd like to run all these tests.

I'm on M1 MacOS. 

Steps to reproduce (basically the repo's README):

```zsh
git clone https://github.com/woocommerce/woocommerce-e2e-boilerplate.git
cd woocommerce-e2e-boilerplate

echo v12 > .nvmrc
nvm use

npm init

nano package.json

> "docker:down": "npx wc-e2e docker:down",
> "docker:ssh": "npx wc-e2e docker:ssh",
> "docker:up": "npx wc-e2e docker:up",
> "test:e2e": "npx wc-e2e test:e2e",
> "test:e2e-debug": "npx wc-e2e test:e2e-debug",
> "test:e2e-dev": "npx wc-e2e test:e2e-d

nano tests/e2e/specs/core.test.js

> const { runShopperTests } = require( '@woocommerce/e2e-core-tests' );
> runShopperTests();

npm i --save-dev @woocommerce/e2e-environment @woocommerce/e2e-utils @woocommerce/api jest
npm install --save-dev @woocommerce/e2e-core-tests 

npm run docker:up
npm run test:e2e
```

```
Tests:       35 failed, 2 skipped, 21 passed, 58 total
```

I'd love to get these working! TIA for any help.

**Comment by rrennick** [comment]
> `runShopperTests();`

We aren't using `runShopperTests` or `runMerchantTests` any more. Those will be deprecated in a future version of the package. You should be able to copy the `tests/e2e/specs/front-end` folder to your project to use/run all the tests.

Also, we should be releasing a new version of the core tests package this week for compatibility changes with WP 5.8.
