### ISSUE TITLE
Update readme to include examples of tests

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce-e2e-boilerplate#12]
Include examples of tests using the packages and building out WC related e2e tests.

**Comment by BrianHenryIE** [comment]
I searched GitHub yesterday for examples and I couldn't find any repo that has implemented this E2E boilerplate. Here's what I was working on – by no means best-practice or complex, and not expected to be included in the readme, but hopefully useful for anyone coming across this issue:

https://github.com/prasidhda/woo-manage-fraud-orders/tree/master/tests/e2e/specs

**Comment by zhongruige** [comment]
Thank you for sharing @BrianHenryIE! 

Actually, would you be mind if we included those in the README as an example to share?

**Comment by BrianHenryIE** [comment]
You're welcome to use it, sure.

**Comment by zhongruige** [comment]
> You're welcome to use it, sure.

Thanks much!
