### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-e2e-boilerplate#30]
WooCommerce repo moved it's contents a bit. Now packages are located at /packages. Also they are not using master as the default branch now it's called trunk. We need to update the links present on our documentation to point to the correct places.

**Comment by rrennick** [comment]
@leonardola Thanks for the reminder. I've put this on our high priority list.

**Comment by leonardola** [comment]
I've already fixed the link on the README on the root of the repository. PR at #31.

**Comment by rodelgc** [comment]
Closing this issue as it appears to be already resolved by the PR mentioned [above](#issuecomment-990170951).
