### ISSUE TITLE
Where is package.json ?

### ISSUE THREAD

**Issue by colmtroy** [woocommerce/woocommerce-e2e-boilerplate#6]
Howdy!

Looking at using this boilerplate for testing a new plugin I'm working on.
I note in the readme the following:

_Modify package.json and add the following under scripts._

I don't see the a package.json in the repo - am I right to assume the readme assumes one already has a package.json in place for their plugin or is there a file missing?

Thanks!

**Comment by lsinger** [comment]
Thanks for the note, @colmtroy! That's correct, we assume an existing extension with an existing `package.json`. 

To resolve this issue, we should probably make this clearer in the README. 

As a second step, it would be nice if we could provide a very basic barebones extension that one could then use to explore the e2e boilerplate.

**Comment by lsinger** [comment]
Just added the note in 5585f30.

**Comment by BrianHenryIE** [comment]
I think it would be good to mention `npm init` in the documentation:

> If your project does not contain a `package.json`, create one using `npm init`.

**Comment by rrennick** [comment]
@BrianHenryIE Thanks, good suggestion.

**Comment by zhongruige** [comment]
Closed with https://github.com/woocommerce/woocommerce-e2e-boilerplate/pull/13
