### ISSUE TITLE
Fails with NPM 7.19.1

### ISSUE THREAD

**Issue by BrianHenryIE** [woocommerce/woocommerce-e2e-boilerplate#7]
After I created `package.json` with `npm init`, it suggested I upgrade NPM. Then this command failed:

```
npm install --save-dev @woocommerce/e2e-environment @woocommerce/e2e-utils jest
```

Solved with:

```
npm install -g npm@6.14.13
```

**Comment by rrennick** [comment]
@BrianHenryIE Thanks for reporting the issue. The packages are developed in the WooCommerce core repository which has some compatibility issues with npm@7.

In the mean time we can add a note to the readme that npm@6 is required.

**Comment by zhongruige** [comment]
Updated README with https://github.com/woocommerce/woocommerce-e2e-boilerplate/pull/13
